@startuml
left to right direction
title 画面遷移図


[*] -down-> メインメニュー画面
メインメニュー画面 -down-> ログイン画面 :ログインを押下
ログイン画面 -> メインメニュー画面 :ログインを押下

メインメニュー画面 -down-> 利用規約画面 :アカウント新規作成を押下
利用規約画面 -down-> アカウント新規作成画面 :アカウント登録を押下
アカウント新規作成画面 -up-> メインメニュー画面 :登録ボタンを押下

メインメニュー画面 -down-> 投稿画面 :投稿を押下
投稿画面 -> メインメニュー画面 :投稿するボタンを押下

メインメニュー画面 -down-> 投稿検索結果画面 :投稿閲覧又は検索を押下
投稿検索結果画面 -down-> 投稿詳細画面 :詳細文を押下
投稿検索結果画面 -down-> 投稿者詳細画面 :投稿者名を押下
投稿詳細画面 --> 投稿者詳細画面 :投稿者詳細画面を押下
投稿者詳細画面 --> 投稿者詳細画面 :フォローを押下
投稿者詳細画面 -> 投稿者詳細画面 :フォロー解除を押下
投稿検索結果画面 -> 投稿検索結果画面 :検索を押下

メインメニュー画面 -down-> チャット一覧画面 :チャットを押下
チャット一覧画面 -> チャット一覧画面 :検索を押下
チャット一覧画面 -down-> チャット画面 :チャットルーム名を押下
チャット一覧画面 -down-> チャットルーム新規作成_更新画面 :作成を押下
チャットルーム新規作成_更新画面 -> チャット一覧画面 :登録/更新を押下
チャット一覧画面 -> チャット一覧画面 :削除を押下

メインメニュー画面 -down-> 里親探し画面 :里親探しを押下
里親探し画面 -down-> 里親探し画面 :検索を押下
里親探し画面 -down-> 里親募集詳細画面 :施設名称を押下
里親探し画面 -down-> 里親募集説明画面 :提携先についてを押下

メインメニュー画面 -down-> 病院検索画面 :病院検索を押下
病院検索画面 -down-> 病院検索画面 :検索を押下
病院検索画面 -down-> 病院情報詳細画面 :施設名を押下
病院検索画面 -down-> 病院検索説明画面 :掲載依頼についてを押下

メインメニュー画面 -down-> ポイント交換画面 :ポイントを押下
ポイント交換画面 -down-> ポイント交換完了画面 :交換するを押下
ポイント交換完了画面 -> マイページ :ホーム画面へ戻るを押下


メインメニュー画面 -down-> マイページ :マイページを押下
マイページ -down-> フォロワー画面 :フォロワーを押下
フォロワー画面 -down-> フォロー画面 :フォロー中を押下
フォロー画面 -down-> フォロワー画面 :フォロワー一覧を押下
フォロワー画面 -down-> フォロー画面 :フォロー中一覧を押下
マイページ -> ポイント交換画面 :ポイントを押下
マイページ -down-> 投稿履歴画面 :投稿履歴を押下
投稿履歴画面 -> 投稿詳細画面 :詳細文を押下
投稿詳細画面 -down-> 投稿編集画面 :編集ボタンを押下
投稿詳細画面 -down-> 投稿削除確認画面 :削除ボタンを押下
投稿削除確認画面 --> 投稿削除完了画面 :はいボタンを押下
投稿削除完了画面 --> 投稿履歴画面 :投稿履歴へ戻るを押下
投稿編集画面 -> 投稿履歴画面 :更新するボタンを押下
マイページ -down-> プロフィール編集画面 :アイコン_アカウント名_プロフィール編集
プロフィール編集画面 -> マイページ :アイコン_アカウント名_プロフィール編集
マイページ -down-> パスワード変更画面 :パスワード変更を押下
パスワード変更画面 -> マイページ :送信ボタンを押下
マイページ -down-> メールアドレス変更画面 :メールアドレス変更を押下
メールアドレス変更画面 -down-> メール認証画面 :メールアドレス変更を押下
メール認証画面 -> メール確認画面 :送信ボタンを押下
メール確認画面 -> メール変更完了画面 :リンクを押下
'あああああああああ 
メール変更完了画面 -> マイページ :OKボタンを押下
' あああああああああ

マイページ -down-> 退会画面 :退会を押下
退会画面 -> ログイン画面 :はいボタンを押下


メインメニュー画面 -down-> 通知一覧 :お知らせ一覧を押下
通知一覧 -> 通知詳細 :タイトルを押下

メインメニュー画面 -down-> ログアウト画面 :ログアウトを押下
ログアウト画面 -down-> ログアウト完了画面 :はいボタンを押下
ログアウト完了画面 -> メインメニュー画面 :OKボタンを押下

メインメニュー画面 -down-> プライバシーポリシー画面 :プライバシーポリシーを押下
メインメニュー画面 -down-> 利用規約画面 :利用規約を押下
利用規約画面 -> プライバシーポリシー画面 :リンクを押下


















' [*] -down-> メニュー1
' メニュー1 -down-> メニュー2

' state メニュー2 {
' 	state "概要" as メニュー2概要
'     state "詳細" as メニュー2詳細
' 	[*] -down-> メニュー2概要
'     メニュー2概要 -down-> メニュー2詳細 : 詳細
'     メニュー2詳細 -down-> メニュー2概要 : 概要
' }

' [*] -down-> メニュー3
' メニュー3 -down-> メニュー4

' state メニュー4 {
' 	state "概要" as メニュー4概要
'     state "詳細" as メニュー4詳細
' 	[*] -down-> メニュー4概要
'     メニュー4概要 -down-> メニュー4詳細 : 詳細
'     メニュー4詳細 -down-> メニュー4概要 : 概要
' }
' @enduml
