@startuml
' left to right direction
title Example State Transition Diagram3


[*] -> メインメニュー画面
メインメニュー画面 -> ログイン :ログインボタンを押下
ログイン -> メインメニュー画面

メインメニュー画面 -> 利用規約 :アカウント新規作成を押下
利用規約 -> アカウント新規作成
アカウント新規作成 -> メインメニュー画面

メインメニュー画面 -> 投稿 :投稿を押下
投稿 -> メインメニュー画面

メインメニュー画面 -> 投稿閲覧 :投稿閲覧を押下
投稿閲覧 -> メインメニュー画面

メインメニュー画面 -> チャット :チャットを押下
チャット -> メインメニュー画面

メインメニュー画面 -> 里親探し :里親探しを押下
里親探し -> メインメニュー画面

メインメニュー画面 -> 病院検索 :病院検索を押下
病院検索 -> メインメニュー画面

メインメニュー画面 -> ポイント :ポイントを押下
ポイント -> メインメニュー画面

メインメニュー画面 -> マイページ :マイページを押下
マイページ -> メインメニュー画面

メインメニュー画面 -> お知らせ一覧 :お知らせ一覧を押下
お知らせ一覧 -> メインメニュー画面

メインメニュー画面 -> ログアウト :ログアウトを押下
ログアウト -> メインメニュー画面




















' [*] -down-> メニュー1
' メニュー1 -down-> メニュー2

' state メニュー2 {
' 	state "概要" as メニュー2概要
'     state "詳細" as メニュー2詳細
' 	[*] -down-> メニュー2概要
'     メニュー2概要 -down-> メニュー2詳細 : 詳細
'     メニュー2詳細 -down-> メニュー2概要 : 概要
' }

' [*] -down-> メニュー3
' メニュー3 -down-> メニュー4

' state メニュー4 {
' 	state "概要" as メニュー4概要
'     state "詳細" as メニュー4詳細
' 	[*] -down-> メニュー4概要
'     メニュー4概要 -down-> メニュー4詳細 : 詳細
'     メニュー4詳細 -down-> メニュー4概要 : 概要
' }
' @enduml
