# Generated by Django 5.1.2 on 2024-11-11 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_at', models.DateTimeField(auto_now_add=True, verbose_name='日時')),
                ('NoticeList', models.TextField(verbose_name='本文')),
            ],
        ),
    ]
