@startuml

actor 利用者

boundary メインメニュー #d5e8d4
boundary 投稿履歴画面 #d5e8d4
boundary 投稿削除完了画面 #d5e8d4

control 投稿情報取得 #f8cecc
control 投稿情報削除 #f8cecc

entity 投稿情報 #dae8fc


利用者 -> メインメニュー : Myアカウントボタンを押下した後、投稿履歴ボタンを押下する
activate 利用者
activate メインメニュー

メインメニュー -> 投稿情報取得 : 起動する()
deactivate メインメニュー
activate 投稿情報取得

投稿情報取得 -> 投稿情報 : 投稿情報を取得する()
activate 投稿情報
投稿情報 --> 投稿情報取得
deactivate 投稿情報

投稿情報取得 -> 投稿履歴画面 : 画面を表示する()
deactivate 投稿情報取得
activate 投稿履歴画面

投稿履歴画面 -> 利用者
deactivate 投稿履歴画面
deactivate 利用者




利用者 -> 投稿履歴画面 : 履歴から投稿の削除ボタンを押下する
activate 投稿履歴画面
activate 利用者

投稿履歴画面 -> 投稿情報削除 : 起動する()
activate 投稿情報削除

投稿情報削除 -> 投稿情報 : 投稿情報を削除する()
activate 投稿情報
投稿情報 --> 投稿情報削除 
deactivate 投稿情報

投稿情報削除 -> 投稿削除完了画面 : 画面を表示する()
deactivate 投稿情報削除
activate 投稿削除完了画面

投稿削除完了画面 -> 投稿履歴画面 : 画面を表示する()
deactivate 投稿削除完了画面

投稿履歴画面 -> 利用者
deactivate 投稿履歴画面
deactivate 利用者
