# Generated by Django 5.1.3 on 2024-11-21 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_fund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='メールアドレス'),
        ),
        migrations.AlterField(
            model_name='user',
            name='screen_name',
            field=models.CharField(blank=True, default='', help_text='128文字以内で入力してください', max_length=128, verbose_name='アカウント名'),
        ),
    ]
