# Generated by Django 5.1.3 on 2024-11-29 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_email_alter_user_screen_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pt_give',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
