# Generated by Django 5.1.2 on 2025-01-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.CharField(blank=True, default='', help_text='200文字以内で入力してください', max_length=200, null=True, verbose_name='プロフィール'),
        ),
    ]
