# Generated by Django 5.1.2 on 2025-01-07 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=30, verbose_name='会える場所')),
                ('address', models.CharField(default='', max_length=50, verbose_name='住所')),
                ('detail', models.CharField(default='', max_length=128, verbose_name='どんな子？')),
                ('hp', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='連絡先')),
            ],
        ),
    ]
