# Generated by Django 5.1.2 on 2025-01-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_adoptlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adoptlist',
            old_name='hp',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='adoptlist',
            old_name='name',
            new_name='place',
        ),
        migrations.AddField(
            model_name='adoptlist',
            name='email',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='メール'),
        ),
        migrations.AddField(
            model_name='adoptlist',
            name='species',
            field=models.CharField(default='', max_length=30, verbose_name='種族'),
        ),
        migrations.AddField(
            model_name='adoptlist',
            name='tel',
            field=models.IntegerField(default=0, verbose_name='電話(ハイフン無し)'),
        ),
    ]
