# Generated by Django 5.1.2 on 2025-01-07 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_adoptlist_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptlist',
            name='title',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='一言紹介(20文字)'),
        ),
    ]
