# Generated by Django 5.1.2 on 2025-01-08 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_adoptlist_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='differential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(blank=True, default='', max_length=50, null=True)),
            ],
        ),
    ]
