# Generated by Django 5.1.2 on 2025-01-08 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_differential'),
    ]

    operations = [
        migrations.DeleteModel(
            name='differential',
        ),
    ]
