# Generated by Django 5.1.2 on 2025-01-22 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_delete_differential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptlist',
            name='tel',
            field=models.CharField(default=0, max_length=13, verbose_name='電話(ハイフン無し)'),
        ),
    ]
