# Generated by Django 5.1.4 on 2025-01-31 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_adoptlist_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icon', verbose_name='画像'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.CharField(blank=True, default='', help_text='200文字以内で入力してください', max_length=200, null=True, verbose_name='プロフィール'),
        ),
    ]
