# Generated by Django 5.1.4 on 2025-01-31 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_user_icon_alter_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.TextField(blank=True, default='', help_text='200文字以内で入力してください', max_length=200, null=True, verbose_name='プロフィール'),
        ),
    ]
