# Generated by Django 5.1.4 on 2025-01-31 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=models.ImageField(blank=True, default='icon/default.png', null=True, upload_to='icon', verbose_name='画像'),
        ),
    ]
