# Generated by Django 5.1.4 on 2025-02-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_user_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='name',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
