# Generated by Django 5.1.4 on 2025-02-18 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_animal'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
