# Generated by Django 5.1.4 on 2025-02-18 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_animal_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pt_temp',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
