@startuml rireki 

actor 利用者 as user
boundary "TopPage\n(メニュー画面)" as TopPage #d5e8d4
boundary "ChatListPage\n(チャット一覧画面)" as ChatListPage #d5e8d4
boundary "ChatPage\n(チャット画面)" as ChatPage #d5e8d4
boundary "404\n(アクセスエラー画面)" as AccessErrorPage #d5e8d4

control "ChatView\n(ページ遷移管理)" as View #f8cecc
control "ChatModel\n(データ処理＆DBアクセス)" as Model #f8cecc
entity "Sqlite3\n(データベース)" as DB #dae8fc


activate Model
activate View
user -> TopPage :チャットボタンを\n押下する
activate TopPage
TopPage -> View :ページ遷移を求める\nIndex()
deactivate TopPage
View -> Model :チャット一覧を取得する\nget_queryset()
Model -> DB :DBアクセス\nDbAccess()
activate DB
DB --> Model
deactivate DB
Model -> View :チャット一覧画面を返却\nSetRooms()
View -> ChatListPage :チャット一覧を表示する\nViewChatListPage()
activate ChatListPage
ChatListPage --> user
user -> ChatListPage :チャットを選択する
ChatListPage -> View :ページ遷移を求める\nPageRequest()
deactivate ChatListPage
View -> Model :アクセス許可状態を取得する\nGetAccess()
Model -> DB :DBアクセス\nDbAccess()
activate DB
DB --> Model
deactivate DB
Model -> View:アクセス状態の返却\nSetAccess()
alt アクセス許可がない場合
    View -> AccessErrorPage:アクセスエラー画面を表示する\nViewAccessError()
    activate AccessErrorPage
    AccessErrorPage --> user
    deactivate AccessErrorPage
end
View -> ChatPage:チャット画面を表示する\nViewChatPage()
activate ChatPage
ChatPage --> user
deactivate View
deactivate ChatPage
deactivate Model

@enduml







user -> TopPage :チャットボタンを\n押下する
activate TopPage
TopPage -> Chat :チャット一覧を取得する\nGetRooms()
deactivate TopPage
activate Chat
Chat -> DB :DBアクセス\nDbAccess()
activate DB
DB --> Chat
deactivate DB
Chat -> Index :チャット一覧画面を返却\nSetRooms()
deactivate Chat
activate Index
Index -> ChatListPage :チャット一覧を表示する\nIndexChatListPage()
deactivate Index
activate ChatListPage
ChatListPage --> user
user -> ChatListPage :チャットを選択する
ChatListPage -> Index :ページ遷移を求める\nPageRequest()
deactivate ChatListPage
activate Index
Index -> Chat :アクセス許可状態を取得する\nGetAccess()
deactivate Index
activate Chat
Chat -> DB :DBアクセス\nDbAccess()
activate DB
DB --> Chat
deactivate DB

alt アクセス許可がない場合
    Chat -> AccessErrorView:エラー情報の返却\nSetAccess()
    activate AccessErrorView
    AccessErrorView -> AccessErrorPage:アクセスエラー画面を表示する\nIndexAccessError()
    deactivate AccessErrorView
    activate AccessErrorPage
    AccessErrorPage --> user
    deactivate AccessErrorPage
end
Chat -> ChatPageView
deactivate Chat
activate ChatPageView
ChatPageView -> ChatPage:チャット画面を表示する\nIndexChatPage()
deactivate ChatPageView
activate ChatPage
ChatPage --> user
' deactivate ChatListPageIndex
deactivate ChatPage

' deactivate Chat

@enduml
